### ISSUE TITLE
test failues: conf.py missing

### ISSUE THREAD

**Issue by sandrotosi** [matthew-brett/sphinxtesters#2]
this is the error i get when running tests with the 0.1.1 version as downloaded from PyPI:

```
I: pybuild base:217: cd /home/morph/deb/build-area/sphinxtesters-0.1.1/.pybuild/cpython2_2.7_sphinxtesters/build; python2.7 -m nose 
..............E...........
======================================================================
ERROR: sphinxtesters.tests.test_pagebuilder.test_bad_pagebuilder
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/morph/deb/build-area/sphinxtesters-0.1.1/.pybuild/cpython2_2.7_sphinxtesters/build/sphinxtesters/tests/test_pagebuilder.py", line 45, in test_bad_pagebuilder
    assert_raises(IOError, TestBadPageBuilder.setup_class)
  File "/usr/lib/python2.7/unittest/case.py", line 473, in assertRaises
    callableObj(*args, **kwargs)
  File "/home/morph/deb/build-area/sphinxtesters-0.1.1/.pybuild/cpython2_2.7_sphinxtesters/build/sphinxtesters/sphinxutils.py", line 161, in setup_class
    raise e
ConfigError: There is a programable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/config.py", line 157, in __init__
    execfile_(filename, config)
  File "/usr/lib/python2.7/dist-packages/sphinx/util/pycompat.py", line 135, in execfile_
    with open(filepath, mode) as f:
IOError: [Errno 2] No such file or directory: 'conf.py'


----------------------------------------------------------------------
Ran 26 tests in 1.492s

FAILED (errors=1)
```

**Comment by matthew-brett** [comment]
Just checking - I think this is fixed now - do you agree?
