### ISSUE TITLE
Installation error with v0.2.3 on Read the Docs

### ISSUE THREAD

**Issue by sr-murthy** [matthew-brett/sphinxtesters#5]
I got an error while trying to build Sphinx docs for one of my projects on Read the Docs - the docs requirements include `sphinxtesters==0.2.3`, which failed to install (in a Python 3.12 instance) with the following error:
```
Collecting sphinxtesters==0.2.3 (from -r docs/requirements.txt (line 1206))
  Downloading sphinxtesters-0.2.3.tar.gz (29 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      /tmp/pip-install-ao0h0f_c/sphinxtesters_a3d5942921044db48959d8b08e696836/versioneer.py:421: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-ao0h0f_c/sphinxtesters_a3d5942921044db48959d8b08e696836/setup.py", line 29, in <module>
          version=versioneer.get_version(),
                  ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-ao0h0f_c/sphinxtesters_a3d5942921044db48959d8b08e696836/versioneer.py", line 1480, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/tmp/pip-install-ao0h0f_c/sphinxtesters_a3d5942921044db48959d8b08e696836/versioneer.py", line 1412, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-ao0h0f_c/sphinxtesters_a3d5942921044db48959d8b08e696836/versioneer.py", line 342, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```
Are you aware of this?

**Comment by matthew-brett** [comment]
Thanks - and no - I wasn't aware.   I've made a new 0.2.4 release to fix this - does it work?

**Comment by sr-murthy** [comment]
Thanks, fixed now by your update.
